#!/bin/bash -e

# Check dependencies
printf "\n---- Checking dependencies ----\n"
# Hard dependencies
#  - slock,xbacklight,feh,alacritty,xsetroot: for filetwm (and default app)
DEPS="slock feh xbacklight alacritty xsetroot make gcc busybox rsync wget"
# Preferred applications
#  - ripgrep,node: suggested by nvchad with neovim
PRFS="mupdf vlc rg node vim tmux"
for dep in $DEPS; do command -v $dep >/dev/null || echo "need: $dep"; done
for dep in $PRFS; do command -v $dep >/dev/null || echo "suggested: $dep"; done
for dep in $DEPS; do command -v $dep >/dev/null || exit 1; done
for dep in $PRFS; do command -v $dep >/dev/null || \
(read -p "Ignore (y)?"; test "$REPLY" == 'y' || exit 1;) done

# Install base code.
printf "\n---- Installing codebase ----\n"
mkdir -p ~/.config
rsync -av --delete --exclude cache filetlignux/ ~/.config/filetlignux

# Build all the things that need compiling or constructing.
# Note that these won't get automatic updates:
# neovim
# You can force all updates with: rm -rf ~/.config/filetlignux/*/cache
for build in filetwm neovim nvchad mimi; do
	printf "\n---- Building $build ----\n"
	cd ~/.config/filetlignux/$build/; make all; cd -
done

# Installing home dir config files.
printf "\n---- Linking HOME dir config files ----\n"
while IFS= read -r file; do
	dest=$(echo "$file" | sed -e 's:^.*/filetlignux/installs/::')
	printf "$dest\n"
	if [[ -L ~/"$dest" && `readlink ~/"$dest"` \
	== `ls -1da ~/.config/filetlignux/installs/"$dest"` ]]; then
		printf "...ok\n"
	else
		if [ -f ~/"$dest" ]; then
			echo "...moving aside (~/$dest.old)"
			mv ~/"$dest" ~/"$dest.old"
		fi
		echo "...installing link (~/$dest)"
		mkdir -p $(dirname ~/"$dest")
		ln -s "$file" ~/"$dest"
	fi
done <<< $(find ~/.config/filetlignux/installs/ -type f -o -type l)

# Prep and initialisation
printf "\n---- Initialising ----\n"
mkdir -p ~/.local/share/vim
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'; echo

printf "\n---- Done ----\n"
