#!/bin/bash -e

# Check dependencies
printf "\n\nChecking dependencies...\n\n"
for dep in slock rsync feh xbacklight firefox nnn mupdf vim make gcc; do
	command -v $dep || (echo "need $dep"; exit 1)
done

# Install base code.
printf "\n\nInstalling codebase...\n\n"
mkdir -p ~/.config
rsync -av --delete filetlignux/ ~/.config/filetlignux

# Build everything that needs to be compiled.
for build in dmenu dwm st flstatus xrootname; do
	printf "\n\nBuilding ${build}...\n\n"
	cd ~/.config/filetlignux/$build/; make; cd -
done

# Install fonts.
mkdir -p ~/.local/share/fonts
find ~/.config/filetlignux/fonts/*/fonts -type f | \
	awk '{printf("ln -f -s %s ~/.local/share/fonts/\n", $1)}' | sh

# Installing home dir config files.
printf "\n\nLinking HOME dir config files...\n\n"
for file in $(find ~/.config/filetlignux/installs/ -type f); do
	dest=$(echo $file | sed -e 's:^.*/filetlignux/installs/::')
	printf "$dest\n"
	if [[ -L ~/$dest && `readlink ~/$dest` \
	== `ls -1a ~/.config/filetlignux/installs/$dest` ]]; then
		printf "...ok\n"
	else
		if [ -f ~/$dest ]; then
			echo "...moving aside (~/$dest.old)"
			mv ~/$dest ~/$dest.old
		fi
		echo "...installing link (~/$dest)"
		mkdir -p $(dirname ~/$dest)
		ln -s $file ~/$dest
	fi
done

# Prep
mkdir -p ~/.vim
