#!/bin/bash -e

# Check we are the root user
if [ "$EUID" -ne 0 ]; then
	printf "please run as root\n"
	exit
fi

# Install the keyboard overrides for mouse buttons
cp mousekeys/70-mousekeys.hwdb /etc/udev/hwdb.d/70-mousekeys.hwdb
udevadm hwdb --update
udevadm trigger

