.TH FILETWM 1

.SH NAME
filetwm \- a palatable lean slice of window manager

.SH KEYBOARD SHORTCUTS
.RS
.TS
tab (@);
r l.
Keys@Action
_
Win+Tab:@open launcher
Win+Shift+Tab:@open terminal
Win+Space:@move window
Win+Alt+Space:@resize window
Win+Ctrl+Space:@tile window
Alt+Enter:@fullscreen window
Win+Enter:@pin window
Win+Alt+Enter:@raise window
(Shift+)Alt+Tab:@switch window, and raise
Win+Up/Down:@switch window
Win+Left/Right:@switch workspace
Win+Shift+Left/Right:@switch workspace with window
Win+[1-9]:@switch workspace
Win+Shift+[1-9]:@move window to workspace
Alt+[1-9]:@add window to workspace
Alt+0:@add window to all workspaces
Alt+F4:@close window
Win+F4:@sleep
Shift+Ctrl+Alt+F4:@quit
.TE
.RE

.SH DESCRIPTION
filetwm is a minimalist window manager for X. It manages windows in tiled and
floating layers, across virtual workspaces, with support for fullscreen and
pinned windows.
.P
In the tiled layer, windows are managed in two columns. The left column is the
primary area and contains one window by default, while the right column is the
stacking area and contains all other windows. The number of primary area
windows can be adjusted to an arbitrary number, along with the primary column
size, by resizing any window in the tile layer.
.P
In the floating layer, windows can be resized and moved freely. All windows
start out floating and can be switched between the tiled layer on demand.
.P
Window focus follows the mouse and clicks will raise a window. If any
floating window is raised, all floating windows will sit above tiled windows.
Fullscreen windows that are not raised will sit behind the tiled layer.
.P
The primary monitor contains a small status bar which contains four sections:
a launcher button (to open applications), the selected window title, a
customisable status pane, and a display of the virtual workspaces. The virtual
workspace pane shows the selected workspace (highlighted), dots to indicate
which workspaces contain windows, and inversed colors when a contained window
has an alert.
.P
Windows have thin borders and indicate the focus state with a highlight color.

.SH USAGE
The primary control interface is intended to be via the keyboard shortcuts
detailed above, along with mouse control for window focus, click-to-raise,
and all sizing movements, but additional mouse controls are supported:
.RS
.TS
tab (@);
r r l.
Area@Button@Action
_
Window Top/Left Border@Button1:@initiate move
Window Bottom/Right Border@Button1:@initiate resize
Launcher Button@Button1:@open launcher
Window Title@Button1:@next window
Window Title@Button3:@previous window
Status Section@Button1:@open help
Virtual Workspaces@Button1:@show workspace
Virtual Workspaces@Button3:@relocate window
.TE
.RE

.SH CUSTOMIZATION
.SS Config plugins
filetwm supports config plugins which can be installed to the system at
.B /etc/config/filetwmconf.so,
or for a user at
.B ~/.config/filetwmconf.so.

.RS
/* filetwmconf.c: Example source config file for filetwm's config plugin,
changing the status bar font size. Build and install config:
cc -shared -fPIC filetwmconf.c -o ~/.config/filetwmconf.so
*/

void _() { extern char *font; font = "monospace:bold:size=5"; }
.RE

Any non-static global variable in the filetwm.c source file can be customised
in this manner. Please see the Configuraton Section.

.SS Status bar
The status bar can be updated by changing the window name of the X root window.
It can be set with the
.BR xsetroot (1)
command.

.SH SYNOPSIS
.B filetwm
.RB [ \-v ]

.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.

