#!/bin/bash

# Put executables into the environment
export PATH=~/.config/filetlignux/bin:${PATH}

# Status bar updater
pkill -f ".*/\.config/filetlignux/filetstatus/filetstatus $DISPLAY"
~/.config/filetlignux/filetstatus/filetstatus $DISPLAY &

# Apply background
feh --bg-tile ~/.config/filetlignux/theme/background.jpg

# Launch the Window Manager
~/.config/filetlignux/dwm/dwm
