#!/bin/bash

# Put executables into the environment
export PATH=~/.config/filetlignux/bin:${PATH}

# Apply background
feh --bg-tile ~/.config/filetlignux/background.jpg

# Launch the Window Manager
~/.config/filetlignux/filetwm/cache/filet-wm/filetwm
